language: php

matrix:
  include:
    - php: 5.2
      dist: precise
      env: TEST=0
    - php: 5.3
      dist: precise
      env: TEST=0
    - php: 5.4
      env: TEST=0
    - php: 5.5
      env: TEST=0
    - php: 5.6
      env: TEST=0
    - php: 7.0
      env: TEST=0
    - php: 7.1
      env: TEST=1
    - php: 7.2
      env: TEST=1
    - php: 7.3
      env: TEST=1
  fast_finish: true

before_script:
  - if [ $TEST == '1' ]; then composer install; fi
  - if [ $TEST == '1' ]; then composer prepare-test; fi

script:
  - php -l src/ReflectionNamespace.php
  - if [ $TEST == '1' ]; then ./vendor/bin/phpcs; fi
  - if [ $TEST == '1' ]; then ./vendor/bin/phpmd src text phpmd.xml; fi
  - if [ $TEST == '1' ]; then composer test; fi
