language: php

php:
  - 7.1.3
  - 7.2.0
  - 7.3.0

before_script:
  - composer install
  - composer prepare-test

script:
  - ./vendor/bin/phpcs
  - ./vendor/bin/phpmd src text phpmd.xml
  - composer test
